version: '3.7'

services: 
    angular_app:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports: 
            - '4200:4200'

    angular_test:
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '9876:9876'    
        command: ["npm","run","test"]

